logging:
  level:
    com.atomist.spring.agent: DEBUG
atomist:
  enabled: true
  debug: true
  url: 'https://webhook-staging.atomist.services/atomist/application/teams/T1L0VDKJP'
  environment:
    domain: '${vcap.application.name:development}:${vcap.application.instance_index:0}'
    pod: 'cf-${HOSTNAME:${random.value}}'