spring:
  application:
    name: demo-service
logging:
  level:
    com.atomist.spring.agent: DEBUG
atomist:
  enabled: true
  debug: true
  url: 'https://webhook-staging.atomist.services/atomist/application/teams/T1L0VDKJP'
  environment:
    domain: 'development:${vcap.application.name:${spring.application.name}}'
    pod: 'cf-${HOSTNAME:${random.value}}'